#!/bin/python3
from gpiozero import  LED
from gpiozero import  Buzzer
from time import sleep

green = LED(16)
yellow = LED(17)
red = LED(18)

buzzer = Buzzer(20)

while True:
    buzzer.on()
    green.on()
    sleep(10)
    green.off()
    buzzer.off()
        
    yellow.on()
    sleep(4)
    yellow.off()
        
    red.on()
    sleep(10)
    red.off()
    
   

